
cbs_to_espn_team_code_mapping = {
    "louisianamonroe-warhawks": "ul-monroe-warhawks",
    "fiu-panthers": "florida-international-panthers",
    "connecticut-huskies": "uconn-huskies",
    "miami-fla-hurricanes": "miami-hurricanes",
    "middle-tenn-blue-raiders": "middle-tennessee-blue-raiders",
    "saint-francis-u-red-flash": "st-francis-pa-red-flash",
    "appalachian-state-mountaineers": "app-state-mountaineers",
    "bethunecookman-wildcats": "bethune-cookman-wildcats",
    "central-connecticut-state-blue-devils": "central-connecticut-blue-devils",
    "albany-great-danes": "ualbany-great-danes",
    "liu-sharks": "long-island-university-sharks",
    "se-missouri-st-redhawks": "southeast-missouri-state-redhawks",
    "arkansaspine-bluff-golden-lions": "arkansas-pine-bluff-golden-lions",
    "southeastern-louisiana-lions": "se-louisiana-lions",
    "hawaii-rainbow-warriors": "hawai'i-rainbow-warriors",
    "etsu-buccaneers": "east-tennessee-state-buccaneers",
    "grambling-state-tigers": "grambling-tigers",
    "gardnerwebb-runnin-bulldogs": "gardner-webb-runnin-bulldogs",
    "delaware-fightin-blue-hens": "delaware-blue-hens",
    "army-west-point-black-knights": "army-black-knights",
    "nc-at-aggies": "north-carolina-at-aggies",
    "mcneese-state-cowboys": "mcneese-cowboys",
    "southern-university-jaguars": "southern-jaguars",
    "citadel-bulldogs": "the-citadel-bulldogs"
}

espn_to_cbs_team_code_mapping = {
    "ul-monroe-warhawks": "louisianamonroe-warhawks",
    "florida-international-panthers": "fiu-panthers",
    "uconn-huskies": "connecticut-huskies",
    "miami-hurricanes": "miami-fla-hurricanes",
    "middle-tennessee-blue-raiders": "middle-tenn-blue-raiders",
    "st-francis-pa-red-flash": "saint-francis-u-red-flash",
    "app-state-mountaineers": "appalachian-state-mountaineers",
    "bethune-cookman-wildcats": "bethunecookman-wildcats",
    "central-connecticut-blue-devils": "central-connecticut-state-blue-devils",
    "ualbany-great-danes": "albany-great-danes",
    "long-island-university-sharks": "liu-sharks",
    "southeast-missouri-state-redhawks": "se-missouri-st-redhawks",
    "arkansas-pine-bluff-golden-lions": "arkansaspine-bluff-golden-lions",
    "se-louisiana-lions": "southeastern-louisiana-lions",
    "hawai'i-rainbow-warriors": "hawaii-rainbow-warriors",
    "east-tennessee-state-buccaneers": "etsu-buccaneers",
    "grambling-tigers": "grambling-state-tigers",
    "gardner-webb-runnin-bulldogs": "gardnerwebb-runnin-bulldogs",
    "delaware-blue-hens": "delaware-fightin-blue-hens",
    "army-black-knights": "army-west-point-black-knights",
    "north-carolina-at-aggies": "nc-at-aggies",
    "mcneese-cowboys": "mcneese-state-cowboys",
    "southern-jaguars": "southern-university-jaguars",
    "the-citadel-bulldogs": "citadel-bulldogs"
}