class Game:
    def __init__(self):
        self.game_id: str
        self.league: str
        self.week: int
        self.year: int
        self.cbs_code: str
        self.espn_code: str
        self.fox_code: str
        self.vegas_code: str
        self.away_team_id: str
        self.home_team_id: str
        self.date: str
        self.time: str
        self.tv_coverage: str
        self.game_finished: int
        self.away_q1_score: int
        self.away_q2_score: int
        self.away_q3_score: int
        self.away_q4_score: int
        self.away_overtime_score: int
        self.away_total_score: int
        self.home_q1_score: int
        self.home_q2_score: int
        self.home_q3_score: int
        self.home_q4_score: int
        self.home_overtime_score: int
        self.home_total_score: int
        self.away_moneyline: str
        self.home_moneyline: str
        self.away_spread: str
        self.home_spread: str
        self.over_under: str
        self.away_win_percentage: str
        self.home_win_percentage: str
        self.stadium: str
        self.city: str
        self.state: str
        self.latitude: float
        self.longitude: float