class Team:
    def __init__(self):
        self.team_id: str
        self.league: str
        self.cbs_code: str
        self.espn_code: str
        self.fox_code: str
        self.vegas_code: str
        self.conference_code: str
        self.conference_name: str
        self.division_name: str
        self.team_name: str
        self.team_mascot: str
        self.power_conference: bool
        self.team_logo_url: str
        self.primary_color: str
        self.alternate_color: str
        self.conference_wins: int
        self.conference_losses: int
        self.conference_ties: int
        self.overall_wins: int
        self.overall_losses: int
        self.overall_ties: int
        self.pass_attempts: str
        self.opp_pass_attempts: str
        self.pass_completions: str
        self.opp_pass_completions: str
        self.completion_percentage: str
        self.opp_completion_percentage: str
        self.pass_yards: str
        self.opp_pass_yards: str
        self.pass_touchdowns: str
        self.opp_pass_touchdowns: str
        self.offense_interceptions: str
        self.defense_interceptions: str
        self.rush_yards: str
        self.opp_rush_yards: str
        self.rush_attempts: str
        self.opp_rush_attempts: str
        self.yards_per_rush: str
        self.opp_yards_per_rush: str
        self.rush_touchdowns: str
        self.opp_rush_touchdowns: str